### PR TITLE
fix/docker-method/seed_and_clean

### PR DESCRIPTION
**Pull request by marceautassin**
Fix seed and clean up on docker-method

### CODE REVIEW

**Comment by gkampitakis** [comment]
Thanks for opening a pr 😄 . Going to have a look and merge it if it looks good

**Comment by marceautassin** [comment]
Had an issue on my M1 mac and founded this solution to make it work (but working well on linux distro). With pleasure to discuss to it.

**Comment by gkampitakis** [comment]
Okay had time to look at it. So the issue was the MongoDB was not seeded correctly? Because my approach is different from yours. Both are valid to me, but if mine doesn't work we could use yours with some changes. My approach was to seed the database on start 

```yaml
volumes:
      - './seed.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
```

hence the script. Yours is to do it programmatically. So the reason is this one ?  
> Had an issue on my M1 mac and founded this solution to make it work (but working well on linux distro). With pleasure to discuss to it.

If so I am happy with your solution. Just some changes 
- remove the volume from `docker-compose`
- we could change the file into `.ts`, 
- and import it after

wdyt ?

**Comment by marceautassin** [comment]
Sounds great! 

I can’t still figure it out why the seed command is not working with my M1 chip. Maybe a docker-compose version for Mac?

**Comment by gkampitakis** [comment]
Great, thanks for noticing this issue and sending a pr 🚀

**Pull request merged**
